packages:
  # cri-o/kubernetes node instead of moby.
  - cri-o kubernetes-node 
  # Adding tools because why not
  - cri-tools

postprocess:
  # add kubelet conf
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    cat <<EOF > /etc/kubernetes/kubelet.conf
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    cgroupDriver: systemd
    cgroupRoot: /
    staticPodPath: /etc/kubernetes/manifests
    systemCgroups: /system.slice
    authentication:
      anonymous:
        enabled: true
      webhook:
        enabled: false
    authorization:
      mode: AlwaysAllow
    EOF
  


    rm /etc/cni/net.d/*

    
    cat <<EOF > /etc/cni/net.d/100-crio-bridge.conflist
    {
      "cniVersion": "0.4.0",
      "name": "bridge-firewalld",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni0",
          "isDefaultGateway": true,
          "isGateway": true,
          "ipMasq": true,
          "ipam": {
            "type": "host-local",
            "subnet": "10.88.0.0/16",
            "routes": [
              {
                "dst": "0.0.0.0/0"
              }
            ]
          }
        },
        { 
          "type": "portmap",
          "capabilities": {
      "portMappings": true
        }
        },
        {
          "type": "firewall",
          "backend":"iptables"
        }
      ]
    }
    EOF


    #!/usr/bin/env bash
    set -xeuo pipefail
    cat <<EOF > /usr/lib/systemd/system/kubelet.service
    [Unit]
    Description=Kubernetes Kubelet Server
    Documentation=https://kubernetes.io/docs/concepts/overview/components/#kubelet https://kubernetes.io/docs/reference/generated/kubelet/
    After=crio.service
    Requires=crio.service

    [Service]
    WorkingDirectory=/var/lib/kubelet
    EnvironmentFile=-/etc/kubernetes/config
    EnvironmentFile=-/etc/kubernetes/kubelet
    ExecStart=/usr/bin/kubelet \
              --config=/etc/kubernetes/kubelet.conf \
              --cgroup-driver=systemd \
              --fail-swap-on=false \
              --container-runtime=remote \
              --container-runtime-endpoint=unix:///var/run/crio/crio.sock \
              --runtime-cgroups=/system.slice/crio.service \
              --runtime-request-timeout=10m \
              --address=127.0.0.1 \
              --hostname-override=127.0.0.1 \
              --logtostderr=true 

    Restart=on-failure
    KillMode=process

    [Install]
    WantedBy=multi-user.target
    EOF

    systemctl enable kubelet
